AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HyperNews - Ultra-fast news aggregator with AI-powered config

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    Runtime: provided.al2023
    Architectures:
      - arm64
    Environment:
      Variables:
        ARTICLES_TABLE: !Ref ArticlesTable
        CONFIG_TABLE: !Ref ConfigTable
        RUST_LOG: info

Resources:
  # ---- DynamoDB ----
  ArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-articles"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: category
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi_pk
          AttributeType: S
      KeySchema:
        - AttributeName: category
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: all-articles
          KeySchema:
            - AttributeName: gsi_pk
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  ConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-config"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  # ---- Secrets Manager ----
  AnthropicApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${AWS::StackName}/anthropic-api-key"
      Description: Anthropic API key for HyperNews admin commands
      SecretString: "PLACEHOLDER_REPLACE_AFTER_DEPLOY"

  # ---- Fetcher Lambda (EventBridge) ----
  FetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-fetcher"
      Handler: bootstrap
      CodeUri: ../target/lambda/news-fetcher/
      MemorySize: 512
      Timeout: 120
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ArticlesTable
        - DynamoDBReadPolicy:
            TableName: !Ref ConfigTable
      Events:
        ScheduledFetch:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
            Description: Fetch RSS feeds every 10 minutes
            Enabled: true

  # ---- API Lambda (HTTP API Gateway) ----
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-api"
      Handler: bootstrap
      CodeUri: ../target/lambda/news-api/
      MemorySize: 256
      Timeout: 10
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ArticlesTable
        - DynamoDBReadPolicy:
            TableName: !Ref ConfigTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi

  # ---- Admin Lambda (HTTP API Gateway) ----
  AdminFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-admin"
      Handler: bootstrap
      CodeUri: ../target/lambda/news-admin/
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          ARTICLES_TABLE: !Ref ArticlesTable
          CONFIG_TABLE: !Ref ConfigTable
          ANTHROPIC_SECRET_ID: !Ref AnthropicApiKeySecret
          RUST_LOG: info
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConfigTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref AnthropicApiKeySecret
      Events:
        AdminCommand:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /api/admin/command
        AdminChanges:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /api/admin/changes
        AdminApply:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /api/admin/changes/{id}/apply
        AdminReject:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /api/admin/changes/{id}/reject

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: "$default"
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
        AllowHeaders:
          - Content-Type

  # ---- S3 + CloudFront for Frontend ----
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-frontend"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: offline.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          # S3 for static files
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ""
          # API Gateway
          - Id: ApiOrigin
            DomainName: !Sub "${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              HTTPSPort: 443
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          Compress: true
        CacheBehaviors:
          - PathPattern: "/api/*"
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac  # AllViewerExceptHostHeader
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            Compress: true
          - PathPattern: "/health"
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
        HttpVersion: http2and3

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  CloudFrontUrl:
    Description: CloudFront Distribution URL
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
  FrontendBucket:
    Description: S3 bucket for frontend
    Value: !Ref FrontendBucket
  ArticlesTableName:
    Description: DynamoDB articles table name
    Value: !Ref ArticlesTable
  ConfigTableName:
    Description: DynamoDB config table name
    Value: !Ref ConfigTable
